name: mlocate # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The mlocate command. Now a snap! # 79 char long summary
description: |
    "mlocate: quickly find files on the filesystem based on their name"
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mlocate-source:
    source: https://git.launchpad.net/ubuntu/+source/mlocate
    source-type: git
    # See 'snapcraft plugins'
    plugin: autotools
    build-packages: [automake1.11, autotools-dev, libtool]
    override-build: |
        automake-1.11 --add-missing
